name: XC16 Compile Check

# Runs on pushes to pull request
on: pull_request

jobs:
  xc16-compile-check:
    name: XC16 Compile Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install XC16
        run: |
          wget https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/xc16-v2.10-full-install-linux64-installer.run
          chmod +x ./xc16-v2.10-full-install-linux64-installer.run
          sudo ./xc16-v2.10-full-install-linux64-installer.run --mode unattended --netservername localhost --debuglevel 4

      - name: Run Compile
        run: |
          /opt/microchip/xc16/v2.10/bin/xc16-gcc -mcpu=33EP256GP502 -I. -c -DBOARD_TYPE_UNIQUE_ID=BOARD_TYPE_ID_ANY -DBOARD_INST_UNIQUE_ID=BOARD_INST_ID_ROCKET -std=c99 -Wall message/msg_actuator.c message/msg_general.c message/msg_gps.c message/msg_recovery.c message/msg_sensor.c util/can_rcv_buffer.c util/can_tx_buffer.c util/safe_ring_buffer.c util/timing_util.c dspic33e/dspic33e_can.c mcp2515/mcp2515.c
